version: "3.9"
services:
  postgres:
    image: postgres
    restart: unless-stopped
    container_name: vortex_postgres
    env_file:
      - ../config/postgres.env
    volumes:
      - postgres:/data/postgres
    ports:
      - "${POSTGRES_PORT:-5440}:5432"
    networks:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    container_name: vortex_pgadmin
    env_file:
      - ../config/pgadmin.env
    volumes:
      - pgadmin:/data/pgadmin
    ports:
      - "${PGADMIN_PORT:-5040}:80"
    networks:
      - postgres
    depends_on:
      - postgres
  redis:
    image: redis
    restart: unless-stopped
    container_name: vortex_redis
    command: --requirepass ${REDIS_PASSWORD}
    env_file:
      - ../config/redis.env
    volumes:
      - redis:/data/redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    networks:
      - redis
networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
volumes:
  postgres:
  pgadmin:
  redis:
